export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const GET_ALL_POSTS_FAILURE = 'GET_ALL_POSTS_FAILURE';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';

export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

export const GET_POST_FAILURE = 'GET_POST_FAILURE';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';

export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';

export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const ENTITY_FAILURE = 'ENTITY_FAILURE';
export const ENTITY_CREATE = 'ENTITY_CREATE';
export const ENTITY_UPDATE = 'ENTITY_UPDATE';
export const ENTITY_FETCH = 'ENTITY_FETCH';
export const ENTITY_DELETE = 'ENTITY_DELETE';
export const SELECT_ENTITY_ITEM = 'SELECT_ENTITY_ITEM';
export const CLEAR_ENTITY_LIST = 'CLEAR_ENTITY_LIST';