# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comment_pb2 as comment__pb2


class CommentStub(object):
    """The Chat service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CensorComment = channel.unary_unary(
                '/comment.Comment/CensorComment',
                request_serializer=comment__pb2.CommentRequest.SerializeToString,
                response_deserializer=comment__pb2.CensorReply.FromString,
                )


class CommentServicer(object):
    """The Chat service definition.
    """

    def CensorComment(self, request, context):
        """Sends a chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CensorComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CensorComment,
                    request_deserializer=comment__pb2.CommentRequest.FromString,
                    response_serializer=comment__pb2.CensorReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comment.Comment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Comment(object):
    """The Chat service definition.
    """

    @staticmethod
    def CensorComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comment.Comment/CensorComment',
            comment__pb2.CommentRequest.SerializeToString,
            comment__pb2.CensorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
